services:
  - type: web
    name: timewise-ai-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DL_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
